### ISSUE TITLE
NoMethodError at /user undefined method `[]' for false:FalseClass

### ISSUE THREAD

**Issue by ssoulless** [Sology/maily_herald#17] opened 2016-02-02 15:04 UTC
Following [this guide](https://github.com/Sology/maily_herald/wiki/Setup-with-'devise'-gem) step by step, after start the server and try to register a new user a confirmation email should be sent through Maily Herald

but I get this instead
```
NoMethodError at /user
undefined method `[]' for false:FalseClass

maily_herald (0.9.3) lib/maily_herald.rb

# Gets the Maily logger.
def logger
  unless MailyHerald::Logging.initialized?
    opts = {
      level: options[:verbose] ? Logger::DEBUG : Logger::INFO,
    }
    opts[:target] = options[:logfile] if options[:logfile]
    MailyHerald::Logging.initialize(opts)
  end
```

**Comment by fabbrro** [comment] 2016-02-03 13:25
I encounter the same error.

Also, when I do
`Daily Herald Paperboy --start`
as shown in the above page, I get
`undefined method `merge 'to false: FalseClass`

**Comment by fabbrro** [comment] 2016-02-05 09:55
I did some test.

I created a new app with devise from scratch (rails 4.2.5.1 and ruby 2.2.4p230).
Now I get no error when a user registers, but no confirmation email is sent.


Running background processing 

	maily_herald paperboy --start

returns this


    [Maily#cli] INFO: Started with options: {:mode=>:paperboy, :action=>:start, :daemon=>true}
    You really should set a logfile if you're going to daemonize
    /Users/fabbrro/.rvm/gems/ruby-2.2.4@testMailyHerald/gems/maily_herald-0.9.3/lib/maily_herald/cli.rb:200:in `daemonize'
    /Users/fabbrro/.rvm/gems/ruby-2.2.4@testMailyHerald/gems/maily_herald-0.9.3/lib/maily_herald/cli.rb:45:in `paperboy'
    /Users/fabbrro/.rvm/gems/ruby-2.2.4@testMailyHerald/gems/maily_herald-0.9.3/bin/maily_herald:10:in `<top (required)>'
    /Users/fabbrro/.rvm/gems/ruby-2.2.4@testMailyHerald/bin/maily_herald:23:in `load'
    /Users/fabbrro/.rvm/gems/ruby-2.2.4@testMailyHerald/bin/maily_herald:23:in `<main>'
    /Users/fabbrro/.rvm/gems/ruby-2.2.4@testMailyHerald/bin/ruby_executable_hooks:15:in `eval'
    /Users/fabbrro/.rvm/gems/ruby-2.2.4@testMailyHerald/bin/ruby_executable_hooks:15:in `<main>’


To further investigate, I'm also trying to setup the [sample application][2]. I created some entity (users) and tried to send them emails (via mail catcher). Until now, even if devise gem is not installed, It seems I have no luck: no message at all when running background processing, no errors, but also no mail is sent. 


  [1]: https://github.com/Sology/maily_herald/wiki/Setup-with-'devise'-gem
  [2]: https://github.com/Sology/maily_testapp

**Comment by ardahaal** [comment] 2016-02-10 15:05
Hello @ssoulless @fabbrro 
I couldn't reproduce Your problem. I did put sample app based on 'devise' wiki page on github so You can check it out → https://github.com/ardahaal/rails_devise_maily
Maybe You could share You app code so I can take a look?

**Comment by fabbrro** [comment] 2016-02-13 18:52
Thank you for your reply Ardahaal!
I'll do some test with your sample app and let you know.

**Comment by ardahaal** [comment] 2016-02-23 16:22
@fabbrro @ssoulless Please check http://stackoverflow.com/questions/35156323/mailyherald-setup-with-devise-gem-error-nomethoderror-at-user/35581752#35581752

**Comment by maggiolino6v** [comment] 2016-02-23 18:57
Thank you @ardahaal. With your help I finally found out what was the problem:

following the github page, I created the file maily_herald.yml trying to configure maily_herald and I had left it empty. Once removed, I was able to solve the problem. 

Thanks to the sample app you posted I understand how to correctly setup and run mail_herald and I could compare the two apps to find the problem.
It's true, how to setup Sidekiq via Procfile is not well specified on wiki page. I was not running it in the right way.
Maily_herald seems to work correctly in my app now. Thanks!

**Comment by ardahaal** [comment] 2016-02-23 19:33
@maggiolino6v No problem:) I'll update wiki page. Thanks again for using MailyHerald.

**Comment by maggiolino6v** [comment] 2016-02-29 18:37
Hello @ardahaal, I would like to ask you if you can also send scheduled mails (i.e. weekly newsletter) with the [application](https://github.com/ardahaal/rails_devise_maily) you created.
No problem with the confirmation mail, but with the periodical one I get an error:
`An error occured and mailing was not sent
wrong number of arguments (1 for 0)`
Obviously I can post the log, but I would like to know if the error only happens to me.
Many thanks

**Comment by maggiolino6v** [comment] 2016-03-01 21:23
Forget about this. Periodical emails have started to work (i don't know what is changed). As the [wiki page suggests](https://github.com/Sology/maily_herald#user-content-defaults-optional), I only had to specify default from and host mailer options in application.rb.

**Comment by ardahaal** [comment] 2016-03-02 07:58
@maggiolino6v Ok. if anything comes up let me know. I'll close this issue now. Feel free to email me if needed: wojtek@sology.eu

**Closed by ardahaal** 2016-03-02 07:58 UTC
